#!/usr/bin/expect -f
# This file is part of Firetunnel project
# Copyright (C) 2018 Firetunnel Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firetunnel --server\r"
set server_spawn $spawn_id
after 100

spawn $env(SHELL)
set client_spawn $spawn_id
send -- "firetunnel\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"0.0.0.0:1119 connected"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Tunnel: 10.10.20.0/24, default gw 10.10.20.1, mtu 1427"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Tunnel: DNS"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"/run/firetunnel/ftc updated"
}

after 100


puts "\nall done\n"
