#!/usr/bin/expect -f
# This file is part of Firetunnel project
# Copyright (C) 2018 Firetunnel Authors
# License GPL v2

set timeout 60
spawn $env(SHELL)
match_max 100000

send -- "firetunnel --server\r"
set server_spawn $spawn_id
after 100

spawn $env(SHELL)
set client_spawn $spawn_id
send -- "firetunnel\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"/run/firetunnel/ftc updated"
}

sleep 1
# disconnect client
puts "disconnecting the client\n"
send  "\003"
after 100

set spawn_id $server_spawn
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"disconnected"
}
after 100

# connect client
puts "connecting the client\n"
set spawn_id $client_spawn
send -- "firetunnel\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"/run/firetunnel/ftc updated"
}

# disconnect server
puts "disconnecting the server\n"
set spawn_id $server_spawn
send  "\003"
after 100

set spawn_id $client_spawn
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"disconnected"
}
after 100

puts "\nall done\n"
