#!/usr/bin/expect -f
# This file is part of Firetunnel project
# Copyright (C) 2018 Firetunnel Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firetunnel --server\r"
set server_spawn $spawn_id
after 100

spawn $env(SHELL)
set client_spawn $spawn_id
send -- "firetunnel\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"/run/firetunnel/ftc updated"
}
sleep 1

spawn $env(SHELL)
set sandox_spawn $spawn_id
send -- "firejail --profile=/run/firetunnel/ftc --private\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Child process initialized"
}
sleep 1

send -- "wget yahoo.com\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"saved"
}
after 100


puts "\nall done\n"
