#!/usr/bin/expect -f
# This file is part of Firetunnel project
# Copyright (C) 2018 Firetunnel Authors
# License GPL v2

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firetunnel --server\r"
set server_spawn $spawn_id
after 100

spawn $env(SHELL)
set client_spawn $spawn_id
send -- "firetunnel\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"/run/firetunnel/ftc updated"
}
sleep 1

spawn $env(SHELL)
set sandox_spawn $spawn_id
send -- "firejail --profile=/run/firetunnel/ftc\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Child process initialized"
}
sleep 1

set timeout 30
send -- "ping -c 1 google.com\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"1 packets transmitted, 1 received"
}
after 100

send -- "ping -c 1 yahoo.com\r"
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"1 packets transmitted, 1 received"
}
after 100

send -- "ping -c 1 reddit.com\r"
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"1 packets transmitted, 1 received"
}
after 100

send -- "ping -c 1 lxer.com\r"
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"1 packets transmitted, 1 received"
}
after 100

send -- "ping -c 1 debian.org\r"
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"1 packets transmitted, 1 received"
}
after 100

send -- "ping -c 1 gentoo.org\r"
expect {
	timeout {puts "TESTING ERROR 8\n";exit}
	"1 packets transmitted, 1 received"
}
after 100

send -- "ping -c 1 github.com\r"
expect {
	timeout {puts "TESTING ERROR 9\n";exit}
	"1 packets transmitted, 1 received"
}
after 100

puts "\nall done\n"
